version: "3.8"

services:
  frontend:
    environment:
      - REACT_APP_INDEXER_ENDPOINT=http://localhost:3003
      - REACT_APP_SERVER_URL=http://localhost:5050
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"

  backend:
    environment:
      - LOG_LEVEL=debug
      - API_HOST=0.0.0.0
      - API_PORT=5050
      - UNSAFE_MODE=true
      - SUPPORTED_NETWORKS=
      - CRON_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - DEFAULT_INDEXER_ENDPOINT=http://localhost:3003
      - FEE_MARKUP=0
      - MULTI_TOKEN_MARKUP=1150000
      - ADMIN_WALLET_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      - ETHERSCAN_GAS_ORACLES=""
      - DEFAULT_API_KEY=""
      - WEBHOOK_URL=""
      - HMAC_SECRET=7d33aeebd9b6fa173d41895a7795c4c9dbd322a3973b25a8482e2c6e5158a042
      - DATABASE_URL=postgresql://arkauser:paymaster@local-setup-db-1:5432/arkadev
      - DATABASE_SCHEMA_NAME="arka"
      - DATABASE_SSL_ENABLED=false
      - DATABASE_SSL_REJECT_UNAUTHORIZED=false
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5050
    ports:
      - "5050:5050"

  admin_frontend:
    environment:
      - REACT_APP_INDEXER_ENDPOINT=http://localhost:3003
      - REACT_APP_SERVER_URL=http://localhost:5050
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    expose:
      - 3002
    ports:
      - "3002:3002"
