version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"

  backend:
    environment:
      - LOG_LEVEL=debug
      - API_HOST=127.0.0.1
      - API_PORT=5050
      - SUPPORTED_NETWORKS=
      - CRON_PRIVATE_KEY=
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5050
    ports:
      - "5050:5050"

  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    expose:
      - 3002
    ports:
      - "3002:3002"