version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5050
    ports:
      - "5050:5050"