version: "3.8"

services:
  frontend:
    environment:
      - REACT_APP_INDEXER_ENDPOINT=http://localhost:3003
      - REACT_APP_SERVER_URL=http://localhost:5050
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"

  backend:
    environment:
      - LOG_LEVEL=debug
      - API_HOST=0.0.0.0
      - API_PORT=5050
      - UNSAFE_MODE=false
      - SUPPORTED_NETWORKS=
      - CRON_PRIVATE_KEY=
      - DEFAULT_INDEXER_ENDPOINT=http://localhost:3003
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5050
    ports:
      - "5050:5050"

  admin_frontend:
    environment:
      - REACT_APP_INDEXER_ENDPOINT=http://localhost:3003
      - REACT_APP_SERVER_URL=http://localhost:5050
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    expose:
      - 3002
    ports:
      - "3002:3002"