name: Trigger Pipeline

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Trigger pipeline
        run: ${{ secrets.PIPELINE_TRIGGER  }}